[tool.poetry]
name = "python-spark"
version = "0.1.0"
description = ""
authors = ["kwchun0520 <ckw05200@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pyspark = "^3.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
